# version: "3"
# services:
#   directus:
#     image: directus/directus:10.10.4
#     ports:
#       - 8055:8055
#     volumes:
#       - ./directus_db:/directus/database
#     environment:
#       KEY: ${KEY}
#       SECRET: ${SECRET}
#       ADMIN_EMAIL: ${ADMIN_EMAIL}
#       ADMIN_PASSWORD: ${ADMIN_PASSWORD}
#       DB_CLIENT: ${DB_CLIENT}
#       DB_FILENAME: ${DB_FILENAME}
#       WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}

#   node:
#     build: .
#     ports:
#       - 3000:3000
#     volumes:
#       - .:/usr/src/app
#     environment:
#       - NODE_ENV=development

version: "3"
services:
  directus:
    image: directus/directus:10.10.4
    ports:
      - 8055:8055
    volumes:
      - ./directus_db:/directus/database
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_FILENAME: ${DB_FILENAME}
      WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}
    networks:
      - app-network

  node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge